#server:
#  host: '1111'

db:
  database: 'barbacode_CourseDbDev'
  host: 'barbacode.com'
  username: 'barbacode_arancibia'
  password: 'pG0W3M6I8l'
  port: 3306
  synchronize: true
  entities: './dist/**/*.entity.js'
